server:
    port: 9001
    context-path: /resource

mybatis:
    mapperLocations: classpath:/com/gclasscn/resource/mapper/*.xml
    typeAliasesPackage: com.gclasscn.resource.domain

logging:
    level:
        root: INFO
        com:
            gclasscn:
                resource:
                   dao: DEBUG
    file: logs/resource.log

database:
    host: 120.27.216.198
    port: 3306
    name: base

spring:
    datasource:
        initialize: false
        url: jdbc:mysql://${database.host}:${database.port}/${database.name}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 1000
        initialSize: 10
        maxWait: 60000
        minIdle: 5
        test-on-borrow: true 
        test-on-return: true
        validation-query: SELECT 1
    http:
        multipart:
            max-file-size: 1024MB
            max-request-size: 1024MB
    thymeleaf:
        cache: false
        cache-period: 0
    template:
        cache: false
        
#layout
layout: content
full-layout: full-layout