server:
    port: 8080
    context-path: /resource

logging:
    level: 
        root: INFO
        org: 
            hibernate: 
                SQL: DEBUG
                type: TRACE
    file: logs/resource.log

database:
    host: 10.1.1.7
    port: 3306
    name: common

spring:
    datasource:
        initialize: false
        url: jdbc:mysql://${database.host}:${database.port}/${database.name}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 1000
        initialSize: 10
        maxWait: 60000
        minIdle: 5
        test-on-borrow: true 
        test-on-return: true
        validation-query: SELECT 1
    http:
        multipart:
            max-file-size: 1024MB
            max-request-size: 1024MB
    thymeleaf:
        cache: false
        cache-period: 0
    template:
        cache: false
    jpa: 
        properties: 
            hibernate: 
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate: 
            ddl-auto: update
        
#layout
layout: content
full-layout: full-layout